# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20170206_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
