# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_userinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='loginCount',
            field=models.IntegerField(default=0),
        ),
    ]
